-- Phase 3 Migration: Signals table and Paper Trades table
-- Required for paper trading execution

BEGIN;

-- 1. Create signals table (for trading signals before execution)
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    model_id UUID REFERENCES models(id) ON DELETE CASCADE,
    instrument_id UUID REFERENCES instruments(id) ON DELETE CASCADE,
    signal_type TEXT NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD')),
    confidence FLOAT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    executed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signals_model ON signals(model_id);
CREATE INDEX IF NOT EXISTS idx_signals_instrument ON signals(instrument_id);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_executed ON signals(executed) WHERE executed = false;

COMMENT ON TABLE signals IS 'Trading signals generated by models, pending execution';

-- 2. Create paper_trades table (for paper trading positions)
CREATE TABLE IF NOT EXISTS paper_trades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    instrument_id UUID REFERENCES instruments(id) ON DELETE CASCADE,
    signal_id UUID REFERENCES signals(id) ON DELETE SET NULL,
    action TEXT NOT NULL CHECK (action IN ('BUY', 'SELL')),
    quantity INTEGER NOT NULL,
    entry_price FLOAT NOT NULL,
    stop_loss FLOAT,
    target FLOAT,
    exit_price FLOAT,
    pnl FLOAT,
    status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'STOPPED', 'TARGET', 'CLOSED', 'EXPIRED')),
    entry_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    exit_time TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_paper_trades_user ON paper_trades(user_id);
CREATE INDEX IF NOT EXISTS idx_paper_trades_instrument ON paper_trades(instrument_id);
CREATE INDEX IF NOT EXISTS idx_paper_trades_status ON paper_trades(status) WHERE status = 'ACTIVE';

COMMENT ON TABLE paper_trades IS 'Paper trading positions for simulation';

-- 3. Add trading_enabled column to instruments if not exists
ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS buy_confidence_threshold FLOAT DEFAULT 0.3;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS sell_confidence_threshold FLOAT DEFAULT 0.5;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS stop_multiplier FLOAT DEFAULT 1.5;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS target_multiplier FLOAT DEFAULT 2.5;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS max_position_size INTEGER DEFAULT 100;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS is_trading_enabled BOOLEAN DEFAULT true;

-- 4. Add sector/industry columns to instruments if not exists
ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS sector TEXT;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS industry TEXT;

ALTER TABLE instruments 
ADD COLUMN IF NOT EXISTS market_cap_category TEXT;

COMMIT;

-- Verification
\echo '✅ Phase 3 Migration Complete'
\echo ''
\echo 'Verification:'
SELECT 'signals' as table_name, COUNT(*) as row_count FROM signals
UNION ALL
SELECT 'paper_trades', COUNT(*) FROM paper_trades;
